/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteCheckoutRouteImport } from './routes/_site/checkout'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteEssentialsRouteImport } from './routes/_site/essentials'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SiteShopRouteImport } from './routes/_site/shop'
import { Route as SiteTermsRouteImport } from './routes/_site/terms'
import { Route as SiteTestimonialsRouteImport } from './routes/_site/testimonials'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as PharmacyDashboardRouteImport } from './routes/pharmacy.dashboard'
import { Route as SiteProductsProductIdRouteImport } from './routes/_site/products/$productId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDbMessagesRouteImport } from './routes/api/db/messages'
import { Route as ApiDbNotificationsRouteImport } from './routes/api/db/notifications'
import { Route as ApiDbOrdersRouteImport } from './routes/api/db/orders'
import { Route as ApiDbPharmaciesRouteImport } from './routes/api/db/pharmacies'
import { Route as ApiDbProductsRouteImport } from './routes/api/db/products'
import { Route as ApiDbReviewsRouteImport } from './routes/api/db/reviews'
import { Route as ApiDbUsersRouteImport } from './routes/api/db/users'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEssentialsRoute = SiteEssentialsRouteImport.update({
  id: '/essentials',
  path: '/essentials',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTestimonialsRoute = SiteTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const PharmacyDashboardRoute = PharmacyDashboardRouteImport.update({
  id: '/pharmacy/dashboard',
  path: '/pharmacy/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteProductsProductIdRoute = SiteProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbMessagesRoute = ApiDbMessagesRouteImport.update({
  id: '/api/db/messages',
  path: '/api/db/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbNotificationsRoute = ApiDbNotificationsRouteImport.update({
  id: '/api/db/notifications',
  path: '/api/db/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbOrdersRoute = ApiDbOrdersRouteImport.update({
  id: '/api/db/orders',
  path: '/api/db/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbPharmaciesRoute = ApiDbPharmaciesRouteImport.update({
  id: '/api/db/pharmacies',
  path: '/api/db/pharmacies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbProductsRoute = ApiDbProductsRouteImport.update({
  id: '/api/db/products',
  path: '/api/db/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbReviewsRoute = ApiDbReviewsRouteImport.update({
  id: '/api/db/reviews',
  path: '/api/db/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDbUsersRoute = ApiDbUsersRouteImport.update({
  id: '/api/db/users',
  path: '/api/db/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/essentials': typeof SiteEssentialsRoute
  '/faq': typeof SiteFaqRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/testimonials': typeof SiteTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/admin/': typeof AdminIndexRoute
  '/products/$productId': typeof SiteProductsProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/db/messages': typeof ApiDbMessagesRoute
  '/api/db/notifications': typeof ApiDbNotificationsRoute
  '/api/db/orders': typeof ApiDbOrdersRoute
  '/api/db/pharmacies': typeof ApiDbPharmaciesRoute
  '/api/db/products': typeof ApiDbProductsRoute
  '/api/db/reviews': typeof ApiDbReviewsRoute
  '/api/db/users': typeof ApiDbUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/account': typeof AccountRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/essentials': typeof SiteEssentialsRoute
  '/faq': typeof SiteFaqRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/testimonials': typeof SiteTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/admin': typeof AdminIndexRoute
  '/products/$productId': typeof SiteProductsProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/db/messages': typeof ApiDbMessagesRoute
  '/api/db/notifications': typeof ApiDbNotificationsRoute
  '/api/db/orders': typeof ApiDbOrdersRoute
  '/api/db/pharmacies': typeof ApiDbPharmaciesRoute
  '/api/db/products': typeof ApiDbProductsRoute
  '/api/db/reviews': typeof ApiDbReviewsRoute
  '/api/db/users': typeof ApiDbUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/essentials': typeof SiteEssentialsRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/testimonials': typeof SiteTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/pharmacy/dashboard': typeof PharmacyDashboardRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/products/$productId': typeof SiteProductsProductIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/db/messages': typeof ApiDbMessagesRoute
  '/api/db/notifications': typeof ApiDbNotificationsRoute
  '/api/db/orders': typeof ApiDbOrdersRoute
  '/api/db/pharmacies': typeof ApiDbPharmaciesRoute
  '/api/db/products': typeof ApiDbProductsRoute
  '/api/db/reviews': typeof ApiDbReviewsRoute
  '/api/db/users': typeof ApiDbUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/login'
    | '/register'
    | '/checkout'
    | '/contact'
    | '/essentials'
    | '/faq'
    | '/shop'
    | '/terms'
    | '/testimonials'
    | '/admin/users'
    | '/pharmacy/dashboard'
    | '/admin/'
    | '/products/$productId'
    | '/api/auth/$'
    | '/api/db/messages'
    | '/api/db/notifications'
    | '/api/db/orders'
    | '/api/db/pharmacies'
    | '/api/db/products'
    | '/api/db/reviews'
    | '/api/db/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/login'
    | '/register'
    | '/checkout'
    | '/contact'
    | '/essentials'
    | '/faq'
    | '/shop'
    | '/terms'
    | '/testimonials'
    | '/admin/users'
    | '/pharmacy/dashboard'
    | '/admin'
    | '/products/$productId'
    | '/api/auth/$'
    | '/api/db/messages'
    | '/api/db/notifications'
    | '/api/db/orders'
    | '/api/db/pharmacies'
    | '/api/db/products'
    | '/api/db/reviews'
    | '/api/db/users'
  id:
    | '__root__'
    | '/_auth'
    | '/_site'
    | '/account'
    | '/admin'
    | '/_auth/login'
    | '/_auth/register'
    | '/_site/checkout'
    | '/_site/contact'
    | '/_site/essentials'
    | '/_site/faq'
    | '/_site/shop'
    | '/_site/terms'
    | '/_site/testimonials'
    | '/admin/users'
    | '/pharmacy/dashboard'
    | '/_site/'
    | '/admin/'
    | '/_site/products/$productId'
    | '/api/auth/$'
    | '/api/db/messages'
    | '/api/db/notifications'
    | '/api/db/orders'
    | '/api/db/pharmacies'
    | '/api/db/products'
    | '/api/db/reviews'
    | '/api/db/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  PharmacyDashboardRoute: typeof PharmacyDashboardRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDbMessagesRoute: typeof ApiDbMessagesRoute
  ApiDbNotificationsRoute: typeof ApiDbNotificationsRoute
  ApiDbOrdersRoute: typeof ApiDbOrdersRoute
  ApiDbPharmaciesRoute: typeof ApiDbPharmaciesRoute
  ApiDbProductsRoute: typeof ApiDbProductsRoute
  ApiDbReviewsRoute: typeof ApiDbReviewsRoute
  ApiDbUsersRoute: typeof ApiDbUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/essentials': {
      id: '/_site/essentials'
      path: '/essentials'
      fullPath: '/essentials'
      preLoaderRoute: typeof SiteEssentialsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/testimonials': {
      id: '/_site/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof SiteTestimonialsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pharmacy/dashboard': {
      id: '/pharmacy/dashboard'
      path: '/pharmacy/dashboard'
      fullPath: '/pharmacy/dashboard'
      preLoaderRoute: typeof PharmacyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/products/$productId': {
      id: '/_site/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof SiteProductsProductIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/messages': {
      id: '/api/db/messages'
      path: '/api/db/messages'
      fullPath: '/api/db/messages'
      preLoaderRoute: typeof ApiDbMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/notifications': {
      id: '/api/db/notifications'
      path: '/api/db/notifications'
      fullPath: '/api/db/notifications'
      preLoaderRoute: typeof ApiDbNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/orders': {
      id: '/api/db/orders'
      path: '/api/db/orders'
      fullPath: '/api/db/orders'
      preLoaderRoute: typeof ApiDbOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/pharmacies': {
      id: '/api/db/pharmacies'
      path: '/api/db/pharmacies'
      fullPath: '/api/db/pharmacies'
      preLoaderRoute: typeof ApiDbPharmaciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/products': {
      id: '/api/db/products'
      path: '/api/db/products'
      fullPath: '/api/db/products'
      preLoaderRoute: typeof ApiDbProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/reviews': {
      id: '/api/db/reviews'
      path: '/api/db/reviews'
      fullPath: '/api/db/reviews'
      preLoaderRoute: typeof ApiDbReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/db/users': {
      id: '/api/db/users'
      path: '/api/db/users'
      fullPath: '/api/db/users'
      preLoaderRoute: typeof ApiDbUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface SiteRouteChildren {
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteEssentialsRoute: typeof SiteEssentialsRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTestimonialsRoute: typeof SiteTestimonialsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductsProductIdRoute: typeof SiteProductsProductIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteEssentialsRoute: SiteEssentialsRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteShopRoute: SiteShopRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteTestimonialsRoute: SiteTestimonialsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductsProductIdRoute: SiteProductsProductIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  PharmacyDashboardRoute: PharmacyDashboardRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDbMessagesRoute: ApiDbMessagesRoute,
  ApiDbNotificationsRoute: ApiDbNotificationsRoute,
  ApiDbOrdersRoute: ApiDbOrdersRoute,
  ApiDbPharmaciesRoute: ApiDbPharmaciesRoute,
  ApiDbProductsRoute: ApiDbProductsRoute,
  ApiDbReviewsRoute: ApiDbReviewsRoute,
  ApiDbUsersRoute: ApiDbUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
